# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.5"
manifest_format = "2.0"
project_hash = "6ef44bab3d60214c12bb49d28775ecfefa6e9e95"

[[deps.MaridIR]]
path = "../MaridIR"
uuid = "0aa8228c-ae90-54ec-b99f-6e73e9362e55"
version = "0.1.0"
